// src/routes/__layout.svelte
<script>
    import '../app.css'

    import Header from '$lib/Header/index.svelte'
    import Footer from '$lib/Footer/index.svelte'
</script>

<div class="layout">
    <Header />

    <div class="layout-content">
        <slot></slot>
    </div>

    <Footer />
</div>

<style>
    .layout {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        align-items: center;
    }

    .layout-content {
        margin-top: 5em;
        flex: 1;
    }
</style>

// src/components/layout/Layout.vue
<template>
  <div class="layout container is-fluid p-0">
    <div class="layout-header">
      <slot name="header"></slot>
    </div>
    <div class="layout-content">
      <slot name="content"></slot>
    </div>
    <div class="layout-footer">
      <slot name="footer"></slot>
    </div>
  </div>
</template>

<script>
  export default {
    name: "Layout"
  }
</script>

<style scoped>
  .layout {
    display: flex;
    flex-flow: column;
    height: 100vh;
  }

  .layout-content {
    flex: 1;
  }

  .layout-footer {
    flex: 0;
    padding: 0;
    min-height: 16em;
  }
</style>
